Repository coostax/addon-firefly-iii, pull requests merged in 2023-09, with the labels that each got.

#33 Update ff 6 0
  firefly-iii/Dockerfile
Labels: enhancement

#35 update finish scripts to remove s6-test
  firefly-iii/build.yaml
  firefly-iii/rootfs/etc/php/8.2/fpm/php-fpm.conf
  firefly-iii/rootfs/etc/php/8.2/fpm/pool.d/www.conf
  firefly-iii/rootfs/etc/services.d/nginx/finish
  firefly-iii/rootfs/etc/services.d/php-fpm/finish
  firefly-iii/rootfs/etc/services.d/php-fpm/run
Labels: bugfix

#30 Update Copyright Data
  README.md
Labels: documentation

#36 Update firefly to version 6.0.23
  INFO.md
  firefly-iii/Dockerfile
Labels: enhancement

#37 Add gh-action to check for updates in Firefly
  .github/workflows/ci.yaml
  .github/workflows/update-version.yml
  firefly-iii/Dockerfile
Labels: enhancement

#38 fix version check action
  .github/workflows/check-new-version.yml
Labels: bugfix

#40 Final fix on update action
  .github/workflows/check-new-version.yml
Labels: bugfix

#39 Update Firefly-iii version
  firefly-iii/Dockerfile
Labels: enhancement

#42 Update Firefly-iii version
  firefly-iii/Dockerfile
Labels: enhancement

#43 Add publish github action
  .github/workflows/check-new-version.yml
  .github/workflows/deploy.yaml
Labels: enhancement
